### ISSUE TITLE
BACnet Binding for Web of Things 

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-binding-templates#144]
I like to start the initiative to formalize an official BACnet binding for the Web of Things. BACnet is an important protocol for building automation and control systems for scenarios like heating, ventilating, and air-conditioning control (HVAC), lighting control, and fire detection systems. Standardized BACnet-based metadata for WoT Thing Descriptions would simplify the onboarding and use of BACnet-based systems for various IoT applications (also see [Smart Buidling](https://w3c.github.io/wot-usecases/#smart-buildings) and [Protocol-Interworking](https://w3c.github.io/wot-usecases/#X-Protocol-Interworking) use cases).  

This thread should be used to collect material, comments, and people who are interested in this initiative.

**Comment by sebastiankb** [comment]
@mjkoster already shared some samples how Thing Description can be defined for BACnet:

- https://github.com/mjkoster/ODM-Examples/blob/master/protocol-descriptor/observable-flow-protocol-descriptor-bacv-223p.td.json
- https://github.com/mjkoster/ODM-Examples/blob/master/protocol-descriptor/observable-flow-protocol-descriptor-bacnet-223p.td.json

**Comment by fennibay** [comment]
Hi, @sebastiankb thanks for logging this issue.

We're also interested in this, and have actually a working draft, but we're open for other proposals as well, main objective in my view is to have an open definition for modelling BACnet devices with WoT TD.

Please find it here: https://github.com/fennibay/wot-bacnet/blob/main/bacnet.ttl

How shall we proceed?

**Comment by egekorkan** [comment]
From the call of 26.01:
- We should also involve Takenaka Corporation (@ashimura and @chachamimm will contact through WoT Japanese CG).
- The result of the work is expected to be a separate document like the Modbus Binding and linked in the list of protocols in the main document

**Comment by gart-labor** [comment]
Hello, 

at the Laboratory for Building Automation at the Cologne University of Applied Sciences, we work with various building automation communication protocols and are interested in working on the BACnet Binding. 

We are already in contact with @sebastiankb .

**Comment by egekorkan** [comment]
Hi @gart-labor , thank you for reaching out and for your interest!

Even though nearly all of our work happens in public, W3C specs still require you to be a W3C member if you want to make contributions in the form of pull requests or commits of any kind. The meetings are also reserved for members but the minutes are public and the results of the discussions land in GitHub comments. If you want to become a W3C member, we would be more than happy to have you on board.

If you cannot become a W3C member at the moment, there are other ways you can contribute:
- We can invite you to some of our meetings where you can provide your opinion on the subject. This has some conditions but it is possible and has happened many times before
- You can contribute via GitHub issues where you provide your opinions, and your implementation results or simply give feedback.
- You can join one of the WoT-related Community Groups (see https://www.w3.org/WoT/cg/) and join the meetings with them since they do not need any membership. They do not write specifications though.
- If you can show your expertise in this domain in some way (not sure exactly what is needed), you can apply to be an invited expert. I am not sure if your comment was written by a person or as to represent the University but only individual people can be invited experts.

Sorry for this kind administrative message but it is important to know this since it will define what kind of contributions you can make :)

**Comment by gart-labor** [comment]
Hello everyone, 

sorry we have been quiet for a month. We had to organise some project-specific administrative things at the university. But now all contracts are signed and we can start working. 

This account is a group account from our lab. My name is Björn Kämper and my github username is "bjoernkaemper".  

@sebastiankb told us about the opportunity to be invited as an expert. If I remember correctly, Prof. Diedrich from the University of Magdeburg is a w3c member and there is the possibility to be invited through him? He knows us and our expertise very well and if this process is possible, I would contact him. 

Greetings from Cologne!

**Comment by egekorkan** [comment]
Hi @gart-labor and @bjoernkaemper. It seems that University of Magdeburg is not a W3C member anymore. Invited Expert application would be possible but it would be only for one specific person and we would need some way that you explain your expertise. I propose to invite you to our call next week and we can discuss together. The person who is interested in an Invited Expert application can send me an email at ege.korkan (at) siemens.com .
