### ISSUE TITLE
Use cases and requirements for protocol binding

### ISSUE THREAD

**Issue by draggett** [w3c/wot-binding-templates#3]
Before we go much further, it would be valuable to gather some use cases and the requirements they imply. Here are some initial ideas for discussion:

* A smart home with an application hub on which people can install apps for the IoT devices they have purchased. The hub supports a range of protocols, e.g. HTTP, Web Sockets, CoAP and Bluetooth. Users can access apps on the hub from their smart phones.  An app is a collection of resources including an application script, and Web resources for the  user interface on the phone. The application script registers a thing with the hub and provides an implementation that includes the code for communicating with IoT devices. This code is platform specific, e.g. using the CoAP and Bluetooth modules for a NodeJS based platform. The application script abstracts the device behaviour in terms of properties, actions and events, decoupling consumers of the thing from the details of the protocol used by the device.

* The user interface for a service for a smart home is implemented as a Web page that runs on a smart phone, and is loaded from a hub/gateway on the home's WiFi local area network. Things are exposed to web page scripts as JavaScript objects in the web page's execution environment. The scripts are decoupled from the messaging with the hub/gateway using a web page library. This library uses WebSockets for asynchronous messaging with simple JSON messages.

* A variant of the previous use case in which the Web page is loaded from an application hub in the cloud. Applications can access things exposed by this hub, other cloud-based hubs, or hubs behind firewalls, e.g. in people's homes.  The hubs are connected via Web protocols, e.g. WebSockets, or HTTP.  There are several ways to support two way asynchronous messaging over HTTP. One involves both end-points acting as HTTP clients and HTTP servers. Another involves the use of HTTP Server-Sent Events, which is essentially the same as CoAP GET + Observe.

* A cloud hub that exposes services as things for easier application development. This uses things as a "narrow waist" to decouple apps from the networking details for accessing these services. Some examples include the weather, and information about opening hours for a zoo.

* A related use case involves subscribing to filtered events from a cloud service. The consumer passes a set of parameters when subscribing that the provider interprets to filter events of interest.

* A smart device that publishes its own things rather than relying on a hub. The device is accessed via CoAP and is able to provide the thing descriptions either by itself or by reference to a cloud server.

Note that I have simplified the above accounts by leaving out details of discovery, security etc., as I don't think these are so important to the requirements for binding templates.

**Comment by draggett** [comment]
The above examples show that for the most part we only need to work on binding templates for Web protocols such as Web Sockets and HTTP.  This is because the applications installed on a local hub/gateway encapsulate the code needed to support local devices whether they are accessed via CoAP, Bluetooth, ZigBee or whatever IoT technologies are involved.

In essence, if the Web of Things is to be useful with commercial IoT devices, then we have to work with what those devices implement rather than requiring them to support a Web of Things standard. We don't need to define protocol bindings as this is the responsibility of the device manufacturer or a third party that provides the installable application for the hub/gateway.  The hub platform will provide libraries that simplify writing the device driver code.  These libraries could, for instance, provide a simple REST interface for CoAP, or a similar interface designed for OCF compliant devices.

For hub to hub, and hub to web page, we would need to define the message exchanges involved whether these are over WebSockets ,  HTTP or another Web protocol. The metadata needed for protocol binding would be very minimal.

**Comment by zolkis** [comment]
> In essence, if the Web of Things is to be useful with commercial IoT devices, then we have to work with what those devices implement rather than requiring them to support a Web of Things standard.

I agree with this, the question is what level of intrusion we need for WoT compatibility. In order that we could talk about a _web_ of such hubs/Things, in connection to web pages, it should be web-like easy to deploy, connect and run/update software for these, regardless if manufacturers or 3rd parties are supposed to provide the hub apps (and deal with protocols, interop and security). 

It seems like in the examples above _hubs_ are analogous to browsers and _Things_ to JS objects usable in web pages intended for the end user. We could achieve this for instance by installing a hypothetical _WoT runtime_ or _WoT servient_ stack on these hubs as a basis for running/managing _apps_, making it analogous to a browser. This is quite intrusive, as requires re-flashing a hub, or requires app support for the hub (with system level permissions).

In order to make this installable stack simpler, we (WoT specifications) could simplify and minimize the interfaces it implements.

> These libraries could, for instance, provide a simple REST interface for CoAP, or a similar interface designed for OCF compliant devices.

Yes, and I think it makes sense to specify such interfaces and their configuration/metadata using a TD format. This part could be standardized in WoT.

In addition, we should investigate whether could we achieve WoT compatibility of hubs without requiring to install a WoT servient stack on to-be-WoT-compatible-devices. But that would impose some requirements on those hubs in order to be WoT compliant.

In essence, there are only two ways to make WoT hubs: either by requiring WoT support for manufacturers, or be requiring a mechanism to install a WoT servient (or system apps in general). In both cases we should make the WoT interface lean and well defined, making possible some kind of automation of downloading support for new WoT devices based on their TD's and the hub's protocol binding TD's. 

On its turn this requires the presence of certain (linkable, describable) WoT-related services that enable this.

**Comment by mmccool** [comment]
There are a set of use cases similar to the above in the Architecture document that we should review and make sure they are aligned.   We should also distinguish "technical use cases" (what the system sees) from "user use cases" (what the user sees).

**Comment by draggett** [comment]
I think the business case for WoT hubs will justify a new breed of hubs if we're successful in respect to generality and security. Note that you could implement a hub on a laptop, smart phone or tablet, although it would be preferable to use a dedicated device that is always on and connected to the local area network.

**Comment by mjkoster** [comment]
The meta use case is a WoT Servient being able to accommodate existing device ecosystems that use standard protocols. The Servient itself may be implemented in hubs, gateways, mobile devices, cloud services, and in other locally connected devices. It may implement a consumed thing interface or an exposed thing interface. 

The device types may include virtual devices and mirror/shadow/proxies for devices and representations of services, etc. as discussed. A lot of this seems to be WoT Architecture. 

The Protocol Binding Template provides the necessary metadata such that a WoT Servient can adapt its communication to the specific protocol requirements of an existing device (or service) ecosystem.

Assuming the WoT Servient has a protocol stack that includes the expected transfer protocol, serializations, and media types, the Protocol Binding Template provides the instructions on which methods, media types, payload formats, and other transfer protocol options to use for various Event, Action, and Property interactions.

**Comment by egekorkan** [comment]
I strongly agree with the last comment by @mjkoster. @draggett if you also agree on this, can you close the issue? We can also keep it as a reference since the initial discussion is indeed interesting.

**Comment by egekorkan** [comment]
Given that there is no further discussion this and that the likelihood that this is continued in the architecture document, I am closing this issue
