### ISSUE TITLE
Is "allOf" in EXAMPLE 6-8 correct?

### ISSUE THREAD

**Issue by yamagile** [w3c/wot-binding-templates#34]
According to [JSON Schema Validation](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-6.7.1), "allOf" means "An instance validates successfully against this keyword if it validates successfully against all schemas defined by this keyword's value.". Would @mjkoster check the EXAMPLE 6-8?

**Comment by mjkoster** [comment]
With this schema, the client should expect to find at least one instance of each item schema included in the allOf array.  This array includes an object schema for LevelData, and an object schema for TransitionTimeData.  I am assuming that this means that the client should look for both items in the returned representation, and is expected to include both items in the transmitted representation. 

It would normally also have "uniqueItems" defined as "true", which includes all items as unique, but since in our case it's not strictly being used for validation, we may not need the extra constraint.

If we use anyOf, it would indicate that all of the items are optional, which might be closer to what we want to express. We could allow an action that sends only LevelData, or only TransitionTimeData.

We could also leave the rule to a higher level definition like iotschema, where we could say that LevelData are mandatory and TransitionTImeData are optional.

Does this make sense? Should we use anyOf?

**Comment by yamagile** [comment]
Thank you for taking time out of your busy schedule. It is not very urgent, so we can also discuss at F2F meeting. Currently I'm not sure, but I think "anyOf" is suited for your cases from my understanding by referring to the "[JSON Schema Validation 6.7](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-6.7)" and "[Understanding JSON Schema (anyOf)](https://spacetelescope.github.io/understanding-json-schema/reference/combining.html?highlight=allof#anyof)".

> anyOf
> To validate against anyOf, the given data must be valid against any (one or more) of the given subschemas.
> ```json
> {
>   "anyOf": [
>     { "type": "string" },
>     { "type": "number" }
>   ]
> }
> ```
> "Yes" is good
> 42 is good
> { "Not a": "string or number" } is not good

Aside to that, I think we can use "items": [] too, like this "[Understanding JSON Schema (Tuple validation)](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#tuple-validation)".

**Comment by egekorkan** [comment]
allOf is not used anymore in the examples, could you close the issue?
