### ISSUE TITLE
BACnet media type

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-binding-templates#357]
In the BACnet binding, there is no usage of `contentType` in the examples so the default mechanism would apply and we would get JSON payloads. However, BACnet is not using JSON afaik. How should we handle this @fennibay ?

**Comment by fennibay** [comment]
I understand that the logical payload is always JSON-based. contentType defines the physical payload on the wire.

BACnet always uses the same ASN.1-based encoding on the wire. It is implemented in the available BACnet stacks.

So from BACnet POV there is not really a need for a contentType field.

But for the sake of completeness we could define one as a default in schema. I checked the [media types on IANA](https://www.iana.org/assignments/media-types/media-types.xhtml), and I don't see anything for BACnet or ASN.1. So we would have to register one on IANA first.

There is [application/bacnet-xdd+zip](https://www.iana.org/assignments/media-types/application/bacnet-xdd+zip), but that one is not for BACnet data, but a special BACnet file format, used for exchanging device descriptions.

**Comment by egekorkan** [comment]
> So from BACnet POV there is not really a need for a contentType field.

The issue is that if we don't define one, a TD process MUST automatically insert application/json (see [here](https://w3c.github.io/wot-thing-description/#sec-default-values)).

The contentType in a TD form doesn't have to be registered in IANA first (at least for now) so it should be fine to define one in the binding spec for now.

**Comment by fennibay** [comment]
Ok, so can we define it like this?

"contentType": "application/X-bacnet"

**Comment by danielpeintner** [comment]
Minor: I usually see lower-case content-types only...

Even though looking int https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1 states some vague statements like

> The type, subtype, and parameter name tokens are case-insensitive.
> Parameter values might or might not be case-sensitive, depending on
> the semantics of the parameter name.

**Comment by egekorkan** [comment]
I propose to use `"application/bacnet-x"` to be aligned with lowercase throughout and starting with bacnet since the other bacnet media type starts like that too. Ideally, something should be registered to IANA. Any thoughts @ektrah and @mjkoster ?

**Comment by ektrah** [comment]
If a media type is strictly needed, registering one with IANA would be the right way to go. No "x-" prefix or similar should be used (see [RFC 6648](https://datatracker.ietf.org/doc/html/rfc6648)). The requirements and registration process for a media type are described in [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838). So we would need to have at least a fully completed registration template. Ideally, there should also be a detailed specification of the media type itself.

Overall, however, I'm not sure how much sense it makes to register the payload formats of all sorts of non-Internet protocols as Internet Media Types.

When a TD consumer invokes an action using HTTP, it needs to know how to serialize the action parameters in the HTTP message body. To do this, the TD needs to specify a media type to use. In the case of CoAP, the TD consumer needs to serialize the data in a CoAP content format, which is more than just a media type. In the case of BACnet, the TD consumer always serializes the data according to the BACnet specification.

This means that even though protocols and serialization formats can be considered orthogonal, I think the _vocabulary_ to specify the serialization format to use is _protocol specific_. And for BACnet, no vocabulary is needed because it is always unambiguously clear.

**Comment by egekorkan** [comment]
I agree that it is redundant information in the case of BACnet but not indicating a contentType can confuse some parsers which should assume JSON as the default for all protocols. This is an annoying limitation of the TD which we can get rid of but we would still need a value for the `contentType` assuming that is still mandatory. We could add some WoT-specific value like `"auto"`, in which case the protocol stack handles it.

Regarding the images: 

- Currently, TD Consumer code does not need to pass JSON or XML to a driver. _Theoretically_, the data structure of the programming language should be passed to the driver, which converts it to the required media type on the fly. If the media type needed is XML, there _should_ be no need to have an intermediary media type like JSON. The programmer of that language should feel "at home" and not need any knowledge of media types.
- I am not sure how this is currently done in implementations that are not JavaScript based. Their input would be much more valuable. @JKRhb could comment on dart_wot implementation.
- I like the second image more than the first one but only relatively :)

**Comment by fennibay** [comment]
I understand `contentType` is useful for example in an HTTP context when the consumer doesn't know if the data should be encoded as JSON or XML in the request/response body.

And I think @ektrah @egekorkan and I agree that we don't need such an indication in BACnet-context.

So the problem is reduced into: when the `contentType` is missing, the consumers default to JSON, and that is not correct for BACnet.

In practice this is not an issue, because no BACnet driver would try to send JSON over the wire. But we should be careful about the concept.

Question: Where is the defaulting to JSON specified? I couldn't find it in the [section on contentType](https://www.w3.org/TR/wot-thing-description/#form-contentType).

Solution ideas:
1. Clarify the defaulting, if missing `contentType` would mean "left to the driver", we can just omit it.
2. Use [octet-stream](https://www.rfc-editor.org/rfc/rfc2046#section-4.5.1)? That just means "arbitrary binary data".

**Comment by ektrah** [comment]
The default value for `contentType` is specified in [Table 31](https://www.w3.org/TR/2023/REC-wot-thing-description11-20231205/#table-default-values-of-vocabulary-terms-that-are-used-when-the-terms-are-not-present-in-a-td) of the TD 1.1 spec.

My preference for TD 2.0 would be for `contentType` to become a protocol-specific vocabulary. That is, instead of `contentType` being shared by all protocols, HTTP would use a new `htv:contentType` vocabulary term; for CoAP [there already exists](https://w3c.github.io/wot-binding-templates/bindings/protocols/coap/index.html#example-request-contentFormat) `cov:contentFormat`; and for BACnet it wouldn't need anything.

For TD 1.1, `application/octet-stream` as a workaround doesn't sound bad to me. The Modbus binding template already [seems to do the same thing](https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#full-td).

**Comment by egekorkan** [comment]
Agree on most points so far. BACnet can use octet-stream like Modbus for now and we can make this optional in the next version. There should be a note that explains that we are doing nothing new for BACnet drivers and they should do what they always did in terms of serialisation.

Regarding making the term protocol specific: While I see the reasoning, I think if the concept is the same, we should have a single word across protocols.

**Comment by danielpeintner** [comment]
Thank you @ektrah for the detailed table 👍

I think I understand why one might want to have (needs?) protocol-specific terms. However, this means that you can no longer make any statements about the data without knowing the protocol. I am myself not sure whether I want that to happen. 
I see (and understand) the argument that one needs to know the protocol anyway, but that may make the `core` TD become an _abstract_ wrapper...

**Comment by JKRhb** [comment]
> * Currently, TD Consumer code does not need to pass JSON or XML to a driver. _Theoretically_, the data structure of the programming language should be passed to the driver, which converts it to the required media type on the fly. If the media type needed is XML, there _should_ be no need to have an intermediary media type like JSON. The programmer of that language should feel "at home" and not need any knowledge of media types.
> 
> * I am not sure how this is currently done in implementations that are not JavaScript based. Their input would be much more valuable. @JKRhb could comment on dart_wot implementation.

As it is the case with node-wot, dart_wot implements the relevant parts of the Scripting API here, where the `value ` of an `InteractionOutput` is mapped to one of the [`DataSchemaValue`](https://w3c.github.io/wot-scripting-api/#dom-dataschemavalue) types `null`, `boolean`, `number`, `string`, `array`, or `object`. As you are further limited to the constraints set by JSON schema, you basically have JSON as an intermediary format when trying to deserialize a payload, which can only be circumvented if you use the binary output (via the `arrayBuffer` method) and deserialize it yourself (without using the codecs provided by node-wot/dart_wot). A classic example for the discrepancy we have here is XML, which is not that well describable by JSON Schema.

Therefore, the schema information is unfortunately not that universally usable, which made me think whether payload bindings should rather each define their own schemas for validation (so the current DataSchemas in the core TD specification would only apply to JSON). As a consequence, the `value` of `InteractionOutput`s could be generic over the format-specific types of `DataSchemaValue`s. All of this of course has the downside of potentially increasing complexity and reducing the content of the core TD, but maybe this is another aspect that could be discussed as part of a general overhaul of how media types are handled within TDs.

**Comment by fennibay** [comment]
> Therefore, the schema information is unfortunately not that universally usable, which made me think whether payload bindings should rather each define their own schemas for validation (so the current DataSchemas in the core TD specification would only apply to JSON).

We had this problem also in BACnet. Simple example: JSON has only one integer type, and BACnet differentiates between signed and unsigned. Solution was to allow BACnet define its own data model under the protocol binding, see `bacv:hasDataType`. Somewhat redundant, but solves the problem completely.

The `contentType` is a bit of a separate problem. Even when you have handled all type system differences, you might still need to distinguish between different formats: XML, JSON, YAML, CBOR... Thankfully we don't have this problem in BACnet.

**Comment by fennibay** [comment]
I created now #390 to address this issue.

**Comment by egekorkan** [comment]
fixed by #390
