### ISSUE TITLE
How do Protocol Bindings work for exposed things?

### ISSUE THREAD

**Issue by mjkoster** [w3c/wot-binding-templates#4]
We have focused on how to use Protocol Bindings to adapt an existing (ecosystem) thing to a Consumed Thing interface.

The discussion around there not being a "Standard WoT Protocol Binding" makes me wonder about using Protocol Bindings to construct Exposed Thing instances. 

Maybe it will be obvious, but I think we should work through an example or 2.

**Comment by mkovatsc** [comment]
My assumption is that the WcposedThing's bindings are dictated by the Servient they are instantiated in. They can only use what protocols are implemented there; asking for something different does not make sense.

There is also no magic, so people still have to make sensible decisions to deploy the right Servient in the right environment. A Servient for the home, for instance, should support the typical home automation protocols. In a factory, the set of protocols should be different...

The app scripts should not care about what exact protocol the Things actually use.

**Comment by mkovatsc** [comment]
More implementation experience shows that all Protocol Binding information is filled into the TD by the Servient.

Choosing Protocol Bindings so far has been done by choosing the right Servient or runtime container or configuring them before instantiating a script that exposes Things. Since runtime containers have to be configured with security metadata as well, I see it as a valid way forward. Also proven, I would say, as it can be compared to Web server configuration such as .htaccess / vhost / ...

Is there still a question around this?
Maybe we should include this information in the deliverable and then close the issue.

**Comment by mjkoster** [comment]
Yes, I think we have now the option to use a TD as an exposed thing constructor and can use this pattern in creating the exposed thing for a proxy, e.g. from IKEA to an http + longpoll event protocol for notifications. I agree we can close this issue.
